name: build-aggressive

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  windows-msvc:
    name: Windows (MSVC, AVX2+IPO)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure (VS 2022, Release)
        shell: pwsh
        run: >
          cmake -S . -B build
          -G "Visual Studio 17 2022"
          -A x64
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON
          -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL
          -DCMAKE_CXX_FLAGS_RELEASE="/O2 /GL /Gw /Gy /Ob3 /Oi /Ot /arch:AVX2 /favor:INTEL64 /fp:fast /GS- /DNDEBUG /D_HAS_ITERATOR_DEBUGGING=0 /D_ITERATOR_DEBUG_LEVEL=0 /D_SECURE_SCL=0"
          -DCMAKE_EXE_LINKER_FLAGS_RELEASE="/LTCG /OPT:ICF /OPT:REF"

      - name: Build (Release)
        shell: pwsh
        run: cmake --build build --config Release --parallel

      # ---- 无输出自检：确认 count 模式没有任何进度/杂项输出 ----
      - name: Smoke test (no extra output in --count)
        shell: pwsh
        run: |
          $exe = Get-ChildItem -Recurse build -Filter *.exe | Where-Object { $_.Name -match 'prime' -or $_.Name -match 'sieve' } | Select-Object -First 1
          if (-not $exe) { throw "Executable not found." }
          $outFile = Join-Path $env:RUNNER_TEMP "stdout.txt"
          $errFile = Join-Path $env:RUNNER_TEMP "stderr.txt"
          # 选择一个中小规模，避免过久；仅做形态检查
          & $exe.FullName --to 10000000 --count --threads 1 1> $outFile 2> $errFile
          $stdout = Get-Content $outFile -Raw
          $stderr = Get-Content $errFile -Raw
          if ($stderr.Trim().Length -ne 0) { throw "Unexpected STDERR: $stderr" }
          if ($stdout -notmatch '^\s*\d+\s*$') { throw "Unexpected STDOUT: $stdout" }

      - name: Package artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-avx2
          path: |
            build/**/Release/*.exe
            build/**/Release/*.pdb

  linux-gcc:
    name: Linux (GCC/Clang, AVX2+POPCNT+BMI2+LTO)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure (Release)
        run: >
          cmake -S . -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON
          -DCMAKE_CXX_FLAGS_RELEASE="-O3 -mavx2 -mpopcnt -mbmi2 -mfma -ffp-contract=fast -DNDEBUG"
          -DCMAKE_EXE_LINKER_FLAGS_RELEASE="-flto"

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Smoke test (no extra output in --count)
        run: |
          exe=$(find build -type f -executable -name "*prime*" -o -name "*sieve*" | head -n1)
          if [ -z "$exe" ]; then echo "Executable not found"; exit 1; fi
          outFile=$(mktemp)
          errFile=$(mktemp)
          "$exe" --to 10000000 --count --threads 1 >"$outFile" 2>"$errFile"
          if [ -s "$errFile" ]; then echo "Unexpected STDERR:"; cat "$errFile"; exit 1; fi
          if ! grep -Eq '^[[:space:]]*[0-9]+[[:space:]]*$' "$outFile"; then
            echo "Unexpected STDOUT:"; cat "$outFile"; exit 1;
          fi

      - name: Package artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-release-avx2-v3
          path: build/**/*
